appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HW2pe3SbL7ht3yrc/HZHZTjNQ7qhJAvQ9vX0u6p4MFJodUDYT5f7NTF/tGoQGmCe3I0lubOWtEX7+GZjmn7mOXjp0QzXF2ntCNMD4bi6VwtnBl9WyJMX8Sz0N9Fk2CMl+tABg7S3hSO+B2CtBheR9aq0Xjd/hfQ33Hnlwh9E3OJLRz9azuPKRChLsy0X7Yiv99SV1+hB5CzyEaawdE8YDaQtx1x+K8p9iRIIyrIBznRJz/LLY+ivxS+OijYF6TGhuq/VqB+Xc/S3EpYQt8GcbPpVen8B8vBTM8CS1hWIF1rGiVxPhYjWxZlIJ1G8fVMuaJadq7veFUbzPHw28WfbRBKl/4ho9iMrrt7EuSNBPbdlPjOoL15n1nOwN3G6fkCnpl2nAMo2HiYsDRTq5ZJhe7r+NS3hBw5CgK5TOjVw4fuUDlxzhZBkvQKCmDZvZ7kh66gnQW3T20jW7L3bcQd1oZ00PHJqTz5nnVztTKM8f1pUSPqloNR/VLGMdUq9dBlw4TTVt3Ll2UMbv83y/fNVqlhq82wm+qC7BN0ovncr6XMHkJiHAswyv5xxP7gy2odLw+RcersAFTlP+uJdITNCwxrgmcbwVVYMxkAym35Wa+pajhhwkLi38BXuIp1pRCKqzgl3HhSkd2imIrngURJ7XzUFqXeUOJqqJh3IVKClxVE=}
