travis:
  secure:
    BINSTAR_TOKEN: Z5NfZtY6b5qPYg5Y2hyMG5m2gQKztgF3vMAAzpsZEmKhL7JRZn86W9ZFdFbB3DL4vrEOBhDKI3f2KYxr2ei/mH/ldbPZNRqg06MPJLt4oWo8aJgfrRJY2HgZy1B/swmy4HTB28S0NY72Le1QobPLDEdjMFvdEQftwTzZCkUaqxAriBp4LTpFSzY88kwtaemrJ1KOGl0U2FGfvNbA4GJXjRgAiIYdYltyJXqhKbra4ouH4i+5yhL/YSxTHcHfjtNVYTBg8OZa/VTHKNMD2eo7q+L3guNHB6nR83k8uQJKoVCmXiThp87oLCxIw78KhnrsKR0bQymO2s2J20yXOfQ4nCrrqAEfoj5wKn7+evCyn2pRaRTcVlwzyokMNd6VZLGn00VWeA82L7eP/4TqCHwHhi48AwAjYeYbUf6mX38LkgrOWP8IKwi9fjy5j8drsi91veIdnYMfS5L3xUJlnvU+e7XJoLifxI10g8abeZHp4Gg3Nr8r7oHEvdpODGziyiJ/TpRMt9t6ETGJX5TzmZLUMUlyGLDZ3spU4lgAz9HWArhyKThKHRhxREMKoJs8VR10EXbNSZf3ZH8Mov/zgU8N6FYjHUkFIfIFl1xrHJ/B1AJbmqWOtcHPk/i/+qA3nfzeJ9Nz1vpiT6jXDsNFIPOmoKoT3D5B3fBHOxqVpRLjDbE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
