travis:
  secure:
    BINSTAR_TOKEN: m11vvttDsxiXaABcbN5vm3x0v8t5gq8E21XapMFtrynYKBQvy6YT2WAi4y7IjTfhnoWQXbo3AXfXMEfu2l+olgPvhXgW7G47ijwgKpt3tMdSTp7+lqcbCUUcObkCXkE+XYZ9M/W05PeisF36iV9eHPIhHO4wKVvFnC8oIk5FOcLQoAupw4K97s8o6zuiMDq1JuCORs8xKn61AlXtKo6Jkq/eXITgo6gc1c9CullrWdYzsHXnTNZonGF3U4hkoh67T3lvLhXiz81JuK8WfjYax0BMmCzc96THnk3jDs/mRNRHAQkS7EvJ20AfH2xA83Kjjt/eeAZ90zs8nrPBJB/iJQdWleEy57XVFxyAya5nLZfUhiyveYbwyP+4t1StTFNGdHLmG4vhn8pxzL9SVBNSp7ChaW7JpO6Ln+aa25YMzakxMJvSrZauNnUWaA60EFKMBBiUd9IiMhRCTquGRheU27N5PKSXDUWz/Ah3tLQD3bLNAG2BfT8odhTWJkuR3+7kQckwWqxaNPzW7aCz1W1rESBGBTCTuxv5LY3lojG6rjC5s/Q4quncbc6iD+wUnf1BAoISDA+nmAMdqVCs69Eee+/Xlc6YqaaPiPAUxCrtzoTL+I32MJLuThl6jNU7M9d7WnMzFybNQeCqU0+UL9SDjv3ms1YjIIeiEfMS1JZabyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
